In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('/media/adesh/My stuff/College Stuff/dataset/pseudo_facebook.csv')

In [3]:
df.head(10)

userid  age  dob_day  dob_year  dob_month  gender  tenure  friend_count  \
0  2094382   14       19      1999         11    male   266.0             0   
1  1192601   14        2      1999         11  female     6.0             0   
2  2083884   14       16      1999         11    male    13.0             0   
3  1203168   14       25      1999         12  female    93.0             0   
4  1733186   14        4      1999         12    male    82.0             0   
5  1524765   14        1      1999         12    male    15.0             0   
6  1136133   13       14      2000          1    male    12.0             0   
7  1680361   13        4      2000          1  female     0.0             0   
8  1365174   13        1      2000          1    male    81.0             0   
9  1712567   13        2      2000          2    male   171.0             0   

   friendships_initiated  likes  likes_received  mobile_likes  \
0                      0      0               0             0   
1                      0      0               0             0   
2                      0      0               0             0   
3                      0      0               0             0   
4                      0      0               0             0   
5                      0      0               0             0   
6                      0      0               0             0   
7                      0      0               0             0   
8                      0      0               0             0   
9                      0      0               0             0   

   mobile_likes_received  www_likes  www_likes_received  
0                      0          0                   0  
1                      0          0                   0  
2                      0          0                   0  
3                      0          0                   0  
4                      0          0                   0  
5                      0          0                   0  
6                      0          0                   0  
7                      0          0                   0  
8                      0          0                   0  
9                      0          0                   0

In [4]:
df = df.drop('friendships_initiated', 1)

In [5]:
df.columns

Index(['userid', 'age', 'dob_day', 'dob_year', 'dob_month', 'gender', 'tenure',
       'friend_count', 'likes', 'likes_received', 'mobile_likes',
       'mobile_likes_received', 'www_likes', 'www_likes_received'],
      dtype='object')

# Subset

In [6]:
client = df[['userid','age', 'dob_day', 'dob_year', 'dob_month']]
client

userid  age  dob_day  dob_year  dob_month
0      2094382   14       19      1999         11
1      1192601   14        2      1999         11
2      2083884   14       16      1999         11
3      1203168   14       25      1999         12
4      1733186   14        4      1999         12
...        ...  ...      ...       ...        ...
98998  1268299   68        4      1945          4
98999  1256153   18       12      1995          3
99000  1195943   15       10      1998          5
99001  1468023   23       11      1990          4
99002  1397896   39       15      1974          5

[99003 rows x 5 columns]

# Merge data


In [7]:
df1 = pd.DataFrame({'employee': ['bob', 'jake', 'tanmay', 'adesh'],
                   'group': ['Accounting', 'engineering','Engineering', 'HR']})


In [8]:
df2 = pd.DataFrame({'employee': ['bob', 'jake', 'tanmay', 'adesh'],
                   'dates': ['2001', '2003','2004', '2005']})


In [9]:
df3 = pd.merge(df1, df2)

In [10]:
df3

employee        group dates
0      bob   Accounting  2001
1     jake  engineering  2003
2   tanmay  Engineering  2004
3    adesh           HR  2005

In [13]:
df.sort_values(by = ['userid'], inplace = True)
df

userid  age  dob_day  dob_year  dob_month  gender  tenure  \
96639  1000008   14        9      1999          9  female   343.0   
34353  1000013   61       26      1952         10  female  1856.0   
85170  1000015  108       10      1905          2  female  1067.0   
45078  1000038   16       25      1997         11    male   170.0   
39963  1000059   15       10      1998          5    male   625.0   
...        ...  ...      ...       ...        ...     ...     ...   
49080  2193485   31       24      1982         12    male   598.0   
18071  2193499   29        4      1984         12    male   263.0   
83587  2193522   22       29      1991          9    male   407.0   
67099  2193538   18        7      1995         11  female     8.0   
55323  2193542   26        5      1987          2    male   644.0   

       friend_count  likes  likes_received  mobile_likes  \
96639          1156    431             198           400   
34353            47    128              55           128   
85170           344      0               1             0   
45078            71      0               0             0   
39963            58     90               8            90   
...             ...    ...             ...           ...   
49080            80    111              32           111   
18071            21      5               0             5   
83587           313     42              27            42   
67099           154    248             330           113   
55323           104      0               0             0   

       mobile_likes_received  www_likes  www_likes_received  
96639                    167         31                  31  
34353                     31          0                  24  
85170                      0          0                   1  
45078                      0          0                   0  
39963                      5          0                   3  
...                      ...        ...                 ...  
49080                     17          0                  15  
18071                      0          0                   0  
83587                     16          0                  11  
67099                    168        135                 162  
55323                      0          0                   0  

[99003 rows x 14 columns]

# Transpose

In [15]:
df.transpose()

96639    34353    85170    45078    39963    14349  \
userid                 1000008  1000013  1000015  1000038  1000059  1000061   
age                         14       61      108       16       15       22   
dob_day                      9       26       10       25       10       24   
dob_year                  1999     1952     1905     1997     1998     1991   
dob_month                    9       10        2       11        5        4   
gender                  female   female   female     male     male     male   
tenure                     343     1856     1067      170      625      429   
friend_count              1156       47      344       71       58       16   
likes                      431      128        0        0       90        0   
likes_received             198       55        1        0        8        0   
mobile_likes               400      128        0        0       90        0   
mobile_likes_received      167       31        0        0        5        0   
www_likes                   31        0        0        0        0        0   
www_likes_received          31       24        1        0        3        0   

                         84757    67119    17182    81177  ...    4248   \
userid                 1000068  1000094  1000103  1000125  ...  2193418   
age                         22       17       65       48  ...       38   
dob_day                      4       23       20        1  ...       10   
dob_year                  1991     1996     1948     1965  ...     1975   
dob_month                    7        4        2        3  ...       10   
gender                    male     male   female   female  ...     male   
tenure                     508      109      595      583  ...      306   
friend_count               325      156       20      277  ...        2   
likes                      128      277        8        0  ...        0   
likes_received              33      109        4        9  ...        0   
mobile_likes                 2      277        8        0  ...        0   
mobile_likes_received       20       92        2        8  ...        0   
www_likes                  126        0        0        0  ...        0   
www_likes_received          13       17        2        1  ...        0   

                         2618     31240    85910    3938     49080    18071  \
userid                 2193460  2193465  2193468  2193473  2193485  2193499   
age                         30       19       57       23       31       29   
dob_day                      1        1       19        1       24        4   
dob_year                  1983     1994     1956     1990     1982     1984   
dob_month                    4        6        2        1       12       12   
gender                    male   female     male     male     male     male   
tenure                     612      139     1940      652      598      263   
friend_count                 1       40      346        2       80       21   
likes                        0     1459      323        0      111        5   
likes_received               0      691      234        0       32        0   
mobile_likes                 0     1459      286        0      111        5   
mobile_likes_received        0      465      105        0       17        0   
www_likes                    0        0       37        0        0        0   
www_likes_received           0      226      129        0       15        0   

                         83587    67099    55323  
userid                 2193522  2193538  2193542  
age                         22       18       26  
dob_day                     29        7        5  
dob_year                  1991     1995     1987  
dob_month                    9       11        2  
gender                    male   female     male  
tenure                     407        8      644  
friend_count               313      154      104  
likes                       42      248        0  
likes_received   

In [16]:
df.shape

(99003, 14)

In [17]:
df.size

1386042

In [18]:
a1 = np.arange(10).reshape(2,5)

In [19]:
a1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
a2 = np.arange(10,20).reshape(2,5)

In [22]:
a2

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [23]:
a1 + a2

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])